=== TarasTsyhanko/ta-lab_java/lab_hw_xml/src/main/resources/xsdGuns.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="collection">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Guns" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="model" type="xs:string"/>
                            <xs:element name="handy" type="xs:string"/>
                            <xs:element name="origin" type="xs:string"/>
                            <xs:element name="material" type="xs:string"/>
                            <xs:element name="ttc">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="carry" type="xs:string"/>
                                        <xs:element name="sightingRange" type="xs:int"/>
                                        <xs:element name="clamp" type="xs:boolean"/>
                                        <xs:element name="optics" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TarasTsyhanko/ta-lab_java/lab_hw_xml/src/main/resources/xmlGuns.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheep type="text/xsl"  href="xlstGuns.xsl" ?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="xsdGuns.xsd">
    <Guns>
        <model>'M-16'</model>
        <handy>TWO_HANDED</handy>
        <origin>USA</origin>
        <material>IRON</material>
        <ttc>
            <carry>MIDDLE</carry>
            <sightingRange>200</sightingRange>
            <clamp>true</clamp>
            <optics>false</optics>
        </ttc>
    </Guns>
    <Guns>
        <model>'Makarov T-4'</model>
        <handy>ONE_HANDED</handy>
        <origin>UKRAINE</origin>
        <material>METAL</material>
        <ttc>
            <carry>CLOSE</carry>
            <sightingRange>1000</sightingRange>
            <clamp>true</clamp>
            <optics>false</optics>
        </ttc>
    </Guns>
    <Guns>
        <model>'CB-98'</model>
        <handy>TWO_HANDED</handy>
        <origin>GERMANY</origin>
        <material>IRON</material>
        <ttc>
            <carry>FAR</carry>
            <sightingRange>1000</sightingRange>
            <clamp>true</clamp>
            <optics>true</optics>
        </ttc>
    </Guns>
</collection>
