=== TarasTsyhanko/ta-lab_java/lab_hw_json/src/main/resources/schemaGuns.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "items": {
    "$id": "#/items",
    "type": "object",
    "innerObject": {
      "$ref": "guns.json"
    },
    "required": [
      "model",
      "handy",
      "origin",
      "ttc",
      "material"
    ],
    "properties": {
      "model": {
        "$id": "#/items/properties/model",
        "type": "string",
        "examples": [
          "AK-47"
        ]
      },
      "handy": {
        "$id": "#/items/properties/handy",
        "type": "string",
        "examples": [
          "TWO_HANDED"
        ]
      },
      "origin": {
        "$id": "#/items/properties/origin",
        "type": "string",
        "examples": [
          "UKRAINE"
        ]
      },
      "ttc": {
        "$id": "#/items/properties/ttc",
        "type": "object",
        "required": [
          "carry",
          "sightingRange",
          "clamp",
          "optics"
        ],
        "properties": {
          "carry": {
            "$id": "#/items/properties/ttc/properties/carry",
            "type": "string",
            "examples": [
              " MIDDLE"
            ]
          },
          "sightingRange": {
            "$id": "#/items/properties/ttc/properties/sightingRange",
            "type": "string",
            "examples": [
              "240"
            ]
          },
          "clamp": {
            "$id": "#/items/properties/ttc/properties/clamp",
            "type": "string",
            "examples": [
              "true"
            ]
          },
          "optics": {
            "$id": "#/items/properties/ttc/properties/optics",
            "type": "string",
            "examples": [
              "false"
            ]
          }
        }
      },
      "material": {
        "$id": "#/items/properties/material",
        "type": "string",
        "examples": [
          "LEAD"
        ]
      }
    }
  }
}

=== TarasTsyhanko/ta-lab_java/lab_hw_json/src/main/resources/guns.json
[
  {
    "model": "AK-47",
    "handy": "TWO_HANDED",
    "origin": "UKRAINE",
    "ttc": {
      "carry": "MIDDLE",
      "sightingRange": "240",
      "clamp": "true",
      "optics": "false"
    },
    "material": "LEAD"
  },
  {
    "model": "TD-54 Bazuka",
    "handy": "TWO_HANDED",
    "origin": "FRENCH",
    "ttc": {
      "carry": "MIDDLE",
      "sightingRange": "240",
      "clamp": "false",
      "optics": "false"
    },
    "material": "IRON"
  }
]
